// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rachita.Infrastructure.Data;

#nullable disable

namespace Rachita.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417162557_AddMedicalGuidelinesKB")]
    partial class AddMedicalGuidelinesKB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Rachita.Core.Entities.Clinic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubscriptionTier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clinics");
                });

            modelBuilder.Entity("Rachita.Core.Entities.ClinicalAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AlertType")
                        .HasColumnType("int");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsResolved")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PrescriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Recommendation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResolutionNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsResolved");

                    b.HasIndex("PatientId");

                    b.HasIndex("PrescriptionId");

                    b.HasIndex("Priority");

                    b.ToTable("ClinicalAlerts");
                });

            modelBuilder.Entity("Rachita.Core.Entities.DoctorProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Bio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BioEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClinicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Credentials")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CredentialsEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignaturePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecialtyEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubSpecialty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubSpecialtyEn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkingHoursFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkingHoursTo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId")
                        .IsUnique();

                    b.ToTable("DoctorProfiles");
                });

            modelBuilder.Entity("Rachita.Core.Entities.DrugInteraction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Drug1")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Drug2")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("EvidenceSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InteractionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Recommendation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("IsActive");

                    b.HasIndex("Drug1", "Drug2");

                    b.HasIndex("Drug1", "Drug2", "ClinicId")
                        .IsUnique()
                        .HasDatabaseName("IX_DrugInteraction_Unique");

                    b.ToTable("DrugInteractions");
                });

            modelBuilder.Entity("Rachita.Core.Entities.MedicalGuideline", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlertMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlertTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConditionValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Recommendation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("TargetKeyword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MedicalGuidelines");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f9f06bf2-4114-41d3-a4c3-e29bc25def43"),
                            AlertMessage = "Warfarin محظور تماماً للحوامل (Teratogenic).",
                            AlertTitle = "🚨 محظور أثناء الحمل!",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Recommendation = "اختر دواء آمن من فئة A/B من FDA مثل Heparin.",
                            RuleType = "Pregnancy",
                            Severity = 2,
                            TargetKeyword = "warfarin"
                        },
                        new
                        {
                            Id = new Guid("b11ea2fb-e265-4f46-95fa-cc4360e7fcba"),
                            AlertMessage = "Methotrexate يسبب تشوهات جنينية خطيرة.",
                            AlertTitle = "🚨 محظور أثناء الحمل!",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Recommendation = "يجب إيقاف الدواء فوراً والتواصل مع المختص.",
                            RuleType = "Pregnancy",
                            Severity = 2,
                            TargetKeyword = "methotrexate"
                        },
                        new
                        {
                            Id = new Guid("eb0d4bae-fc09-4ff3-be76-3a7cb1d31c0a"),
                            AlertMessage = "Isotretinoin دواء مسخ فئة X.",
                            AlertTitle = "🚨 تشوهات جنينية!",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Recommendation = "ممنوع قطعياً.",
                            RuleType = "Pregnancy",
                            Severity = 2,
                            TargetKeyword = "isotretinoin"
                        },
                        new
                        {
                            Id = new Guid("6d525fc0-f925-41e9-a3b0-2f96cfb05ebd"),
                            AlertMessage = "Misoprostol يسبب تقلصات رحمية عنيفة وإجهاض.",
                            AlertTitle = "🚨 خطر الإجهاض!",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Recommendation = "ممنوع للحوامل إلا في حالات الإجهاض الطبي المتعمد.",
                            RuleType = "Pregnancy",
                            Severity = 2,
                            TargetKeyword = "misoprostol"
                        },
                        new
                        {
                            Id = new Guid("bd7db024-fbfa-42f1-aa15-842cdbcdce16"),
                            AlertMessage = "أدوية ACE محظورة لأنها تؤثر على كلى الجنين.",
                            AlertTitle = "⚠️ تحذير حمل",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Recommendation = "استخدم بدائل آمنة لضغط الدم (مثل Methyldopa أو Labetalol).",
                            RuleType = "Pregnancy",
                            Severity = 2,
                            TargetKeyword = "ace inhibitor"
                        },
                        new
                        {
                            Id = new Guid("566af869-25f0-466d-886f-a5cadd7921a2"),
                            AlertMessage = "Amoxicillin محظور - المريض مسجل لديه حساسية من مجموعة البنسلين.",
                            AlertTitle = "⚠️ حساسية البنسلين!",
                            ConditionValue = "penicillin",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Recommendation = "استخدم مضاد حيوي بديل من فئة Macrolide (مثل Azithromycin).",
                            RuleType = "Allergy",
                            Severity = 2,
                            TargetKeyword = "penicillin_to_amoxicillin"
                        },
                        new
                        {
                            Id = new Guid("dcff7cf6-3635-430c-ab2b-8739cf9d268a"),
                            AlertMessage = "Penicillin محظور - المريض مسجل لديه حساسية من هذا الدواء.",
                            AlertTitle = "⚠️ حساسية البنسلين!",
                            ConditionValue = "penicillin",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Recommendation = "استخدم مضاد حيوي بديل من فئة Macrolide أو Cephalosporin متأخر.",
                            RuleType = "Allergy",
                            Severity = 2,
                            TargetKeyword = "penicillin_to_penicillin"
                        },
                        new
                        {
                            Id = new Guid("b1f51ee8-c2b6-4ac4-95b7-7dc5e20dabb5"),
                            AlertMessage = "الأطفال أقل من 5 سنوات يحتاجون لحساب جرعات دقيق يعتمد على الوزن.",
                            AlertTitle = "👶 تنبيه الأطفال (< 5 سنوات)",
                            ConditionValue = "5",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Recommendation = "استخدم صيغة mg/kg لحساب الجرعة وتأكد من التركيز المناسب (شراب/قطرات).",
                            RuleType = "PediatricAge",
                            Severity = 1,
                            TargetKeyword = "general"
                        },
                        new
                        {
                            Id = new Guid("ebf2a792-5d9c-48c0-8d5f-14fc7cfc4ae5"),
                            AlertMessage = "قد يعاني المرضى المسنون من انخفاض في التصفية الكلوية وحساسية متزايدة للأدوية (تأثير بنزوديازيبين، أدوية مضادة للكولين).",
                            AlertTitle = "👴 تنبيه كبار السن (> 65 سنة)",
                            ConditionValue = "65",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Recommendation = "ابدأ بجرعة أقل بـ 50% (Start low, go slow) ويفضل فحص وظائف الكلى (eGFR).",
                            RuleType = "GeriatricAge",
                            Severity = 1,
                            TargetKeyword = "general"
                        },
                        new
                        {
                            Id = new Guid("b8d2eb9d-dcb1-447a-ad85-ab54e3d3606a"),
                            AlertMessage = "يجب تعديل جرعات الأدوية التي تُطرح عن طريق الكلى.",
                            AlertTitle = "⚙️ مريض قصور كلوي",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Recommendation = "استخدم حاسبة الجرعة المعتمدة على eGFR للمضادات الحيوية الخاصة.",
                            RuleType = "ChronicDisease",
                            Severity = 1,
                            TargetKeyword = "kidney"
                        },
                        new
                        {
                            Id = new Guid("7a612154-18f4-4dfa-bae0-1090f488de1d"),
                            AlertMessage = "يجب تعديل جرعات الأدوية الكلوية.",
                            AlertTitle = "⚙️ مريض قصور كلوي",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Recommendation = "افحص الكرياتينين وعدل الجرعة تبعاً.",
                            RuleType = "ChronicDisease",
                            Severity = 1,
                            TargetKeyword = "كلى"
                        });
                });

            modelBuilder.Entity("Rachita.Core.Entities.MedicationTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedicinesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("IsActive");

                    b.HasIndex("Specialty");

                    b.ToTable("MedicationTemplates");
                });

            modelBuilder.Entity("Rachita.Core.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int>("AgeCategory")
                        .HasColumnType("int");

                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BloodGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChronicDiseases")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CurrentMedicationsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Height")
                        .HasColumnType("float");

                    b.Property<string>("IdentityNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPregnant")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedicationHistoryJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PreexistingConditionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.HasIndex("Name");

                    b.HasIndex("Phone");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Rachita.Core.Entities.PatientRiskProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasAsthma")
                        .HasColumnType("bit");

                    b.Property<bool>("HasAutoimmune")
                        .HasColumnType("bit");

                    b.Property<bool>("HasDiabetes")
                        .HasColumnType("bit");

                    b.Property<bool>("HasHeartDisease")
                        .HasColumnType("bit");

                    b.Property<bool>("HasHypertension")
                        .HasColumnType("bit");

                    b.Property<bool>("HasKidneyDisease")
                        .HasColumnType("bit");

                    b.Property<bool>("HasLiverDisease")
                        .HasColumnType("bit");

                    b.Property<bool>("HasThyroidDisease")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBreastfeeding")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPostSurgery")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPregnant")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastRiskAssessmentAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("OnAnticoagulants")
                        .HasColumnType("bit");

                    b.Property<bool>("OnImmunosuppressants")
                        .HasColumnType("bit");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("RiskScore")
                        .HasColumnType("int");

                    b.Property<string>("SpecialNotes")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId")
                        .IsUnique()
                        .HasDatabaseName("IX_PatientRiskProfile_PatientId_Unique");

                    b.ToTable("PatientRiskProfiles");
                });

            modelBuilder.Entity("Rachita.Core.Entities.Prescription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Diagnosis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Prescriptions");
                });

            modelBuilder.Entity("Rachita.Core.Entities.PrescriptionMedicine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DrugInteractionRisk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Indication")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MedicineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PrescriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RouteOfAdministration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarningsAndContraindications")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PrescriptionId");

                    b.ToTable("PrescriptionMedicines");
                });

            modelBuilder.Entity("Rachita.Core.Entities.SyncAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangedByUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperationType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("SyncAuditLogs");
                });

            modelBuilder.Entity("Rachita.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClinicId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Rachita.Core.Entities.VitalSign", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Diastolic")
                        .HasColumnType("int");

                    b.Property<string>("ExtraVitalsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PrescriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Sugar")
                        .HasColumnType("int");

                    b.Property<int?>("Systolic")
                        .HasColumnType("int");

                    b.Property<double?>("Temperature")
                        .HasColumnType("float");

                    b.Property<double?>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PrescriptionId")
                        .IsUnique();

                    b.ToTable("VitalSigns");
                });

            modelBuilder.Entity("Rachita.Core.Entities.ClinicalAlert", b =>
                {
                    b.HasOne("Rachita.Core.Entities.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Rachita.Core.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Rachita.Core.Entities.Prescription", "Prescription")
                        .WithMany()
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Clinic");

                    b.Navigation("Patient");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("Rachita.Core.Entities.DoctorProfile", b =>
                {
                    b.HasOne("Rachita.Core.Entities.Clinic", "Clinic")
                        .WithOne()
                        .HasForeignKey("Rachita.Core.Entities.DoctorProfile", "ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("Rachita.Core.Entities.DrugInteraction", b =>
                {
                    b.HasOne("Rachita.Core.Entities.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("Rachita.Core.Entities.MedicationTemplate", b =>
                {
                    b.HasOne("Rachita.Core.Entities.Clinic", "Clinic")
                        .WithMany()
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("Rachita.Core.Entities.Patient", b =>
                {
                    b.HasOne("Rachita.Core.Entities.Clinic", "Clinic")
                        .WithMany("Patients")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("Rachita.Core.Entities.PatientRiskProfile", b =>
                {
                    b.HasOne("Rachita.Core.Entities.Patient", "Patient")
                        .WithOne("PatientRiskProfile")
                        .HasForeignKey("Rachita.Core.Entities.PatientRiskProfile", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Rachita.Core.Entities.Prescription", b =>
                {
                    b.HasOne("Rachita.Core.Entities.User", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Rachita.Core.Entities.Patient", "Patient")
                        .WithMany("Prescriptions")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Rachita.Core.Entities.PrescriptionMedicine", b =>
                {
                    b.HasOne("Rachita.Core.Entities.Prescription", "Prescription")
                        .WithMany("PrescriptionMedicines")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("Rachita.Core.Entities.User", b =>
                {
                    b.HasOne("Rachita.Core.Entities.Clinic", "Clinic")
                        .WithMany("Users")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("Rachita.Core.Entities.VitalSign", b =>
                {
                    b.HasOne("Rachita.Core.Entities.Prescription", "Prescription")
                        .WithOne("VitalSign")
                        .HasForeignKey("Rachita.Core.Entities.VitalSign", "PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("Rachita.Core.Entities.Clinic", b =>
                {
                    b.Navigation("Patients");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Rachita.Core.Entities.Patient", b =>
                {
                    b.Navigation("PatientRiskProfile");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("Rachita.Core.Entities.Prescription", b =>
                {
                    b.Navigation("PrescriptionMedicines");

                    b.Navigation("VitalSign");
                });
#pragma warning restore 612, 618
        }
    }
}
