import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  bool get isArabic => locale.languageCode == 'ar';

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static final Map<String, Map<String, String>> _localizedValues = {
    'ar': {
      'app_title': 'عيادة راشيتا الذكية',
      'prescription': 'وصفة طبية',
      'patients': 'المرضى',
      'dashboard': 'الإحصائيات',
      'profile': 'الملف',
      'settings': 'الإعدادات',
      'dark_mode': 'الوضع الداكن',
      'language': 'اللغة',
      'arabic': 'العربية',
      'english': 'English',
      'coming_soon': 'مميزات قادمة قريباً 🚀',
      'cloud_backup': 'النسخ الاحتياطي السحابي لحماية البيانات',
      'ai_assistant': 'مساعد الذكاء الاصطناعي للتشخيص',
      'appointments': 'جدولة المواعيد الذكية',
      'billing': 'الفواتير والحسابات الإلكترونية',
      'soon_badge': 'قريباً',
      
      // Settings Extra
      'customization': 'التخصيص والواجهة',
      'cloud_management': 'إدارة الحساب السحابي',
      'clinic_analysis': 'تحليل الحساب والعيادة',
      'new_prescription_dash': 'بدء وصفة طبية جديدة',
      'new_prescription_sub': 'اختر مريضاً لبدء كتابة الروشتة فوراً',
      'clinic_analysis_dash': 'تحليل العيادة',
      'clinic_analysis_sub': 'مراجعة الأداء وسجلات المزامنة',
      'medical_tip_title': 'نصيحة طبية اليوم',
      'medical_tip_content': 'تذكر أن دقة المؤشرات الحيوية تساعد النظام الذكي على تقديم اقتراحات أدق.',
      
      // Patient List
      'add_new_patient': 'إضافة مريض جديد 👤',
      'edit_patient': 'تعديل بيانات مريض ✏️',
      'full_name': 'الاسم الكامل للمريض',
      'phone_number': 'رقم الهاتف للتواصل',
      'age': 'العمر',
      'gender': 'الجنس',
      'male': 'ذكر',
      'female': 'أنثى',
      'add_patient': 'إضافة مريض',
      'search_patient_hint': 'ابحث عن مريض بالاسم أو الهاتف...',
      'no_registered_patients': 'لا يوجد مرضى مُسجلين',
      'no_search_results': 'لا توجد نتائج مطابقة',
      'no_phone': 'بدون هاتف',
      'visits': 'زيارة',
      'cancel': 'إلغاء',
      'save': 'حفظ التعديلات',
      'edit': 'تعديل البيانات',
      'delete': 'حذف المريض',
      'confirm_delete': 'تأكيد الحذف',
      'confirm_delete_content': 'هل أنت متأكد من حذف المريض "{name}"؟ سيتم حذف كافة السجلات التابعة له.',
      'yes': 'نعم، حذف',
      'no': 'تراجع',
      'patient_already_exists': 'هذا المريض موجود مسبقاً في السجل ⚠️',

      // Dashboard
      'welcome_doctor': 'أهلاً دكتور/ ',
      'new_doctor': 'جديد',
      'clinic_dashboard_summary': 'إليك ملخص سريع لأداء العيادة اليوم',
      'loading_stats': 'جاري تحميل الإحصائيات...',
      'stats_error': 'خطأ في تحميل الإحصائيات:',
      'patients_today': 'مرضى اليوم',
      'urgent_cases': 'الحالات الحرجة',
      'total_prescriptions': 'إجمالي الوصفات',
      'weekly_visits_history': 'تاريخ الزيارات الأسبوعية',
      'not_enough_data': 'لا توجد بيانات كافية لعرض المخطط 📊',
      'visit_chart': 'زيارة',
      'top_diagnoses': 'أعلى التشخيصات تسجيلاً',
      'no_diagnoses_yet': 'لم يتم تسجيل تشخيصات بعد',
      'cases_recorded': 'حالة مُسجلة في العيادة',
      'top_medicines': 'الأدوية الأكثر تداولاً',
      'no_medicines_yet': 'لم يتم كتابة أي أدوية بعد',
      'times_prescribed': 'مرة ظهرت في وصفات سابقة',

      // Prescription
      'write_prescription': 'كتابة وصفة طبية',
      'guest_visit': 'زيارة سريعة',
      'guest_warning': 'أنت تكتب وصفة طبية حرة لن تُحفظ بسجل أي مريض.',
      'link_to_patient': 'ربط بمريض لحفظ الوصفة',
      'previous_visits': 'زيارات سابقة',
      'choose_patient': 'اختيار المريض 👤',
      'link_success': 'تم الربط وتفعيل الحفظ التلقائي بنجاح ✨',
      'diagnosis_notes': 'التشخيص والملاحظات',
      'main_diagnosis': 'التشخيص الرئيسي',
      'additional_notes': 'ملاحظات إضافية (تُحفظ ولا تُطبع)',
      'medicines_and_doses': 'الأدوية والجرعات',
      'medicines_count': 'أدوية',
      'no_medicines_added': 'لم يتم إضافة أدوية للوصفة',
      'print_prescription': 'معاينة وطباعة الوصفة',
      'complete_doctor_profile': 'برجاء إكمال ملف الطبيب في الإعدادات أولاً',
      'edit_medicine': 'تعديل بيانات ',
      'dosage': 'الجرعة',
      'frequency': 'التكرار',
      'freq': 'التكرار',
      'duration': 'المدة',
      'pill': 'قرص',
      'spoon': 'ملعقة',
      'spray': 'بخة',
      'once_a_day': 'مرة واحدة',
      'twice_a_day': 'مرتان',
      'three_times': 'ثلاث مرات يومياً',
      'five_days': '5 أيام',
      'seven_days': '7 أيام',
      'one_month': 'شهر',
      'search_medicine': 'ابحث عن دواء...',
      'no_results': 'لا توجد نتائج',
      'custom_medicine': 'إضافة كدواء حر',

      // Profile
      'save_success': 'تم حفظ بيانات الطبيب بنجاح ✅',
      'save_error': 'خطأ أثناء الحفظ:',
      'edit_profile': 'تعديل الملف',
      'doctor_title': 'د. ',
      'clinic_or_center': 'العيادة أو المركز',
      'contact_phone': 'الهاتف للتواصل',
      'address': 'العنوان',
      'working_hours': 'ساعات الدوام',
      'stamp_and_signature': 'الختم والتوقيع',
      'edit_personal_info': 'تعديل الملف الشخصي',
      'personal_info': 'المعلومات الشخصية',
      'doctor_full_name': 'اسم الطبيب الكامل (عربي)',
      'doctor_name_en': 'اسم الطبيب الكامل (English)',
      'medical_specialty': 'التخصص الطبي (عربي)',
      'specialty_en': 'التخصص الطبي (English)',
      'clinic_name': 'اسم العيادة',
      'license_number': 'رقم الترخيص الطبي',
      'credentials': 'المؤهلات العلمية (عربي)',
      'credentials_en': 'المؤهلات العلمية (English)',
      'main_phone': 'رقم التواصل الرئيسي',
      'hours_from': 'دوام من',
      'hours_to': 'دوام إلى',
      'identity_and_stamp': 'الهوية والختم',
      'clinic_logo': 'شعار العيادة',
      'personal_stamp': 'الختم الشخصي',
      'choose_image': 'اختر صورة',
      'required_field': 'هذا الحقل مطلوب',

      // License & Route
      'route_of_admin': 'مسار التناول',
      'total_units': 'الكمية',
      'route_oral': 'فموي',
      'route_injection': 'حقن',
      'route_topical': 'موضعي',
      'route_inhaler': 'استنشاق',
      'route_drops': 'قطرات',
      'route_suppository': 'تحميلة',
      'allow_generic': 'صرف المثيل',
      'preview_prescription': 'معاينة الوصفة',
      'profile_subtitle': 'تحديث بيانات الطبيب، التخصص، والترخيص',
      'stats_subtitle': 'نظرة عامة على نشاط العيادة اليومي والأسبوعي',
      'clinic_stats': 'إحصائيات العيادة',
      'from_yesterday': 'مقارنة بالأمس',
      'total_patients': 'إجمالي المسجلين',
      'prescriptions_this_month': 'وصفة هذا الشهر',
      'all_patients': 'جميع المرضى',
      'personal_photo': 'الصورة الشخصية',
      'doctor_bio': 'المعلومات الإضافية / السيرة الذاتية',
      'attachments': 'الصور والتحاليل المرفقة',
      'add_attachment': 'إضافة صورة/تحليل 📸',
      'symptoms': 'الأعراض التي يعاني منها المريض',
      'diagnoses_suggestions': 'تشخيصات سابقة',
      'notes_suggestions': 'ملاحظات سابقة',
      'gallery': 'المعرض',
      'patient_vitals': 'المؤشرات الحيوية',
      'expand_vitals': 'عرض كل المؤشرات',
      'weight': 'الوزن',
      'height': 'الطول',
      'head_circ': 'محيط الرأس',
      'blood_pressure': 'ضغط الدم',
      'sugar': 'السكري',
      'temperature': 'الحرارة',
      'pulse': 'النبض',
      'va': 'حدة الإبصار VA',
      'iop': 'ضغط العين IOP',
      'specialty': 'التخصص',
      'blood_group': 'فصيلة الدم',
    },
    'en': {
      'app_title': 'Rachita Smart Clinic',
      'prescription': 'Rx',
      'patients': 'Patients',
      'dashboard': 'Dashboard',
      'profile': 'Profile',
      'settings': 'Settings',
      'dark_mode': 'Dark Mode',
      'language': 'Language',
      'arabic': 'العربية',
      'english': 'English',
      'coming_soon': 'Coming Soon 🚀',
      'cloud_backup': 'Cloud Sync & Data Backup',
      'ai_assistant': 'AI Diagnosis Assistant',
      'appointments': 'Smart Appointments Scheduling',
      'billing': 'Billing & E-Accounting',
      'soon_badge': 'SOON',

      // Settings Extra
      'customization': 'Customization & UI',
      'cloud_management': 'Cloud Account Management',
      'clinic_analysis': 'Clinic Analysis & Reports',
      'new_prescription_dash': 'Start New Prescription',
      'new_prescription_sub': 'Select a patient to start writing Rx immediately',
      'clinic_analysis_dash': 'Clinic Analysis',
      'clinic_analysis_sub': 'Review performance and sync logs',
      'medical_tip_title': 'Medical Tip of the Day',
      'medical_tip_content': 'Accurate vitals help the AI provide safer treatment suggestions.',

      // Patient List
      'add_new_patient': 'Add New Patient 👤',
      'edit_patient': 'Edit Patient Details ✏️',
      'full_name': 'Patient Full Name',
      'phone_number': 'Phone Number',
      'age': 'Age',
      'gender': 'Gender',
      'male': 'Male',
      'female': 'Female',
      'add_patient': 'Add Patient',
      'search_patient_hint': 'Search by name or phone...',
      'no_registered_patients': 'No registered patients yet.',
      'no_search_results': 'No search results found.',
      'no_phone': 'No Phone',
      'visits': 'Visits',
      'cancel': 'Cancel',
      'save': 'Save Changes',
      'edit': 'Edit details',
      'delete': 'Delete patient',
      'confirm_delete': 'Confirm Delete',
      'confirm_delete_content': 'Are you sure you want to delete patient "{name}"? All related medical records will be erased.',
      'yes': 'Yes, Delete',
      'no': 'Cancel',
      'patient_already_exists': 'Patient already exists in records ⚠️',

      // Dashboard
      'welcome_doctor': 'Welcome Dr. ',
      'new_doctor': 'Unset',
      'clinic_dashboard_summary': 'Quick summary of your clinic\'s performance today',
      'loading_stats': 'Loading statistics...',
      'stats_error': 'Error loading stats:',
      'patients_today': 'Patients Today',
      'urgent_cases': 'Urgent Cases',
      'total_prescriptions': 'Total Prescriptions',
      'weekly_visits_history': 'Weekly Visits History',
      'not_enough_data': 'Not enough data for chart 📊',
      'visit_chart': 'visit',
      'top_diagnoses': 'Top Diagnoses Recorded',
      'no_diagnoses_yet': 'No diagnoses recorded yet',
      'cases_recorded': 'cases recorded in clinic',
      'top_medicines': 'Most Prescribed Medicines',
      'no_medicines_yet': 'No medicines prescribed yet',
      'times_prescribed': 'times appeared in past prescriptions',

      // Prescription
      'write_prescription': 'Write Prescription',
      'guest_visit': 'Quick Visit',
      'guest_warning': 'You are writing a free prescription without tying it to a patient record.',
      'link_to_patient': 'Link to a patient for auto-save',
      'previous_visits': 'previous visits',
      'choose_patient': 'Select Patient 👤',
      'link_success': 'Linked and auto-save enabled successfully ✨',
      'diagnosis_notes': 'Diagnosis & Notes',
      'main_diagnosis': 'Main Diagnosis',
      'additional_notes': 'Additional notes (Hidden from print)',
      'medicines_and_doses': 'Medicines & Doses',
      'medicines_count': 'medicines',
      'no_medicines_added': 'No medicines added to the prescription',
      'print_prescription': 'Preview & Print Prescription',
      'complete_doctor_profile': 'Please complete doctor profile in settings first',
      'edit_medicine': 'Edit ',
      'dosage': 'Dosage',
      'frequency': 'Frequency',
      'freq': 'Freq.',
      'duration': 'Duration',
      'pill': 'Pill',
      'spoon': 'Spoon',
      'spray': 'Spray',
      'once_a_day': 'Once a day',
      'twice_a_day': 'Twice a day',
      'three_times': 'Three times a day',
      'five_days': '5 Days',
      'seven_days': '7 Days',
      'one_month': 'One Month',
      'search_medicine': 'Search for a medicine...',
      'no_results': 'No results',
      'custom_medicine': 'Add as custom medicine',

      // Profile
      'save_success': 'Doctor profile saved successfully ✅',
      'save_error': 'Error saving:',
      'edit_profile': 'Edit Profile',
      'doctor_title': 'Dr. ',
      'clinic_or_center': 'Clinic or Center',
      'contact_phone': 'Contact Phone',
      'address': 'Address',
      'working_hours': 'Working Hours',
      'stamp_and_signature': 'Stamp & Signature',
      'edit_personal_info': 'Edit Personal Info',
      'personal_info': 'Personal Information',
      'doctor_full_name': 'Doctor Full Name (Arabic)',
      'doctor_name_en': 'Doctor Full Name (English)',
      'medical_specialty': 'Medical Specialty (Arabic)',
      'specialty_en': 'Medical Specialty (English)',
      'clinic_name': 'Clinic Name',
      'license_number': 'Medical License No.',
      'credentials': 'Credentials / Titles (Arabic)',
      'credentials_en': 'Credentials / Titles (English)',
      'main_phone': 'Main Phone',
      'hours_from': 'Hours From',
      'hours_to': 'Hours To',
      'identity_and_stamp': 'Identity & Stamp',
      'clinic_logo': 'Clinic Logo',
      'personal_stamp': 'Personal Stamp',
      'choose_image': 'Choose Image',
      'required_field': 'This field is required',

      // License & Route
      'route_of_admin': 'Route',
      'total_units': 'Qty',
      'route_oral': 'Oral',
      'route_injection': 'Injection',
      'route_topical': 'Topical',
      'route_inhaler': 'Inhaler',
      'route_drops': 'Drops',
      'route_suppository': 'Suppository',
      'allow_generic': 'Allow Generic',
      'preview_prescription': 'Preview Prescription',
      'profile_subtitle': 'Update doctor info, specialty, and license',
      'stats_subtitle': 'Overview of daily and weekly clinic activity',
      'clinic_stats': 'Clinic Statistics',
      'from_yesterday': 'from yesterday',
      'total_patients': 'Total Patients',
      'prescriptions_this_month': 'prescriptions this month',
      'all_patients': 'All Patients',
      'personal_photo': 'Personal Photo',
      'doctor_bio': 'Bio / Additional Info',
      'attachments': 'Images & Lab Attachments',
      'add_attachment': 'Add Image/Lab 📸',
      'symptoms': 'Patient Symptoms',
      'diagnoses_suggestions': 'Past Diagnoses',
      'notes_suggestions': 'Past Notes',
      'gallery': 'Gallery',
      'patient_vitals': 'Patient Vitals',
      'expand_vitals': 'Expand Vitals',
      'weight': 'Weight',
      'height': 'Height',
      'head_circ': 'Head Circ.',
      'blood_pressure': 'Blood Pressure',
      'sugar': 'Blood Sugar',
      'temperature': 'Temperature',
      'pulse': 'Pulse',
      'va': 'Visual Acuity (VA)',
      'iop': 'Intraocular Pressure (IOP)',
      'specialty': 'Specialty',
      'blood_group': 'Blood Group',
    },
  };

  String tr(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension LocalizationExtension on BuildContext {
  String tr(String key) {
    return AppLocalizations.of(this)?.tr(key) ?? key;
  }
}